apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../configuration
  - tf-demo-node-hello-world.deployment.yml
  - tf-demo-node-hello-world.service.yml
  - tf-demo-python-hello-world.deployment.yml
  - tf-demo-python-hello-world.service.yml
  - tf-demo-node-hello-world.serviceaccount.yml
  - tf-demo-python-hello-world.serviceaccount.yml
